
project_id = "mwjlshfqddwvtatwhynx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
inbucket_port = 54324

[storage]
enabled = true
